# Sync secret data values between Kubernetes namespaces

This example demonstrates transferring a specific secret data value like `spec.password` into a secret of a different namespace.

The password value can be created using this command: `echo -n supersecret | base64 -w0`

## Manifest

[source,yaml]
----
---
apiVersion: v1 <1>
kind: Secret
metadata:
  name: source-secret
  namespace: source-namespace
type: Opaque
data:
  password: c3VwZXJzZWNyZXQ= # "supersecret"
---
apiVersion: espejote.io/v1alpha1
kind: ManagedResource
metadata:
  annotations:
    syn.tools/description: | <2>
      Manages `spec.password` in the `secret` resource.

      The content of `spec.password` is copied from the source secret.
  labels:
    app.kubernetes.io/name: secret-sync
  name: secret-sync
  namespace: destination-namespace
spec:
  triggers:
  - name: source-secret <3>
    watchResource:
      apiVersion: v1
      kind: Secret
      name: source-secret
      namespace: source-namespace
  context:
  - name: destination-secret <4>
    resource:
      apiVersion: v1
      kind: Secret
      name: destination-secret
      namespace: destination-namespace
  serviceAccountRef:
    name: secret-sync <5>
  template: |
    local esp = import 'espejote.libsonnet';

    if esp.triggerName() == 'source-secret' then
      {
        apiVersion: 'v1',
        kind: 'Secret',
        metadata: {
          name: 'destination-secret',
          namespace: 'destination-namespace',
        },
        data: {
          'testpassword': esp.triggerData().resource.data['password']
        }
      }
----
<1> Example of a source `Secret`. It might already exist.
<2> Description of the `ManagedResource`.
We recommend a description that explains the purpose of every `ManagedResource` and how it works.
<3> Trigger for the `ManagedResource`.
The `ManagedResource` will be re-rendered when the resource changes.
`watchContextResource` copies a definition from the context to the trigger and shares the cache.
<4> Context for the `ManagedResource`.
Always a list of zero or more resources.
The resources is added to the `esp.context()` object and can be used in the `template`.
The name is the object key in the context.
<5> Service account the `ManagedResource` uses to authenticate to the API server.
The service account must have permissions to get, list, and watch the resources in the context and trigger.
It must also have permissions to create, update and patch the returned resources.
See <<rbac,RBAC>> for the roles required for this resource.
<6> Mapping of the secret values.
The values is taken as is as original base64 encoded string without newline.

### RBAC [[rbac]]

[source,yaml]
----
---
apiVersion: v1 <1>
kind: ServiceAccount
metadata:
  name: sync-secret
  namespace: destination-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-sync
  namespace: source-namespace
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - source-secret
    verbs:
      - get
      - list
      - watch <2>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-sync
  namespace: source-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-sync
subjects:
  - kind: ServiceAccount
    name: secret-sync
    namespace: destination-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-sync
  namespace: destination-namespace
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - destination-secret
    verbs:
      - get
      - list
      - watch
      - create <3>
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-sync
  namespace: destination-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-sync
  namespace: source-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-sync
subjects:
  - kind: ServiceAccount
    name: secret-sync
    namespace: destination-namespace
----
<1> The `ServiceAccount` is used to authenticate to the API server.
<2> The `ManagedResource` needs to be able to watch the `Secret` resources to build the context.
<3> The `ManagedResource` needs to be able to create, update and patch the destination `Secret` resource.
