# permissions for end users to view clustermanagedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: espejote
    app.kubernetes.io/managed-by: kustomize
  name: clustermanagedresource-viewer-role
rules:
- apiGroups:
  - espejo.appuio.io
  resources:
  - clustermanagedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - espejo.appuio.io
  resources:
  - clustermanagedresources/status
  verbs:
  - get
