# permissions for end users to edit clustermanagedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: espejote
    app.kubernetes.io/managed-by: kustomize
  name: clustermanagedresource-editor-role
rules:
- apiGroups:
  - espejo.appuio.io
  resources:
  - clustermanagedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - espejo.appuio.io
  resources:
  - clustermanagedresources/status
  verbs:
  - get
