# permissions for end users to view clustermanagedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustermanagedresource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: espejote
    app.kubernetes.io/part-of: espejote
    app.kubernetes.io/managed-by: kustomize
  name: clustermanagedresource-viewer-role
rules:
- apiGroups:
  - espejote.io
  resources:
  - clustermanagedresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - espejote.io
  resources:
  - clustermanagedresources/status
  verbs:
  - get
