# permissions for end users to edit managedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: espejote
    app.kubernetes.io/managed-by: kustomize
  name: managedresource-editor-role
rules:
- apiGroups:
  - espejo.appuio.io
  resources:
  - managedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - espejo.appuio.io
  resources:
  - managedresources/status
  verbs:
  - get
