# This rule is not used by the project espejote itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over espejote.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: espejote
    app.kubernetes.io/managed-by: kustomize
  name: plugin-admin-role
rules:
- apiGroups:
  - espejote.io
  resources:
  - plugins
  verbs:
  - '*'
- apiGroups:
  - espejote.io
  resources:
  - plugins/status
  verbs:
  - get
