---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - espejote.io
  resources:
  - clustermanagedresources
  - managedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - espejote.io
  resources:
  - clustermanagedresources/finalizers
  - managedresources/finalizers
  verbs:
  - update
- apiGroups:
  - espejote.io
  resources:
  - clustermanagedresources/status
  - managedresources/status
  verbs:
  - get
  - patch
  - update
