// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package applygroup

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoopKind-0]
	_ = x[ApplyKind-1]
	_ = x[ApplyGroupConfigKind-2]
	_ = x[DeleteKind-3]
	_ = x[GroupKind-4]
}

const _Kind_name = "NoopKindApplyKindApplyGroupConfigKindDeleteKindGroupKind"

var _Kind_index = [...]uint8{0, 8, 17, 37, 47, 56}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
