apiVersion: espejote.io/v1alpha1
kind: JsonnetLibrary
metadata:
  annotations:
    description: |
      A collection of Jsonnet utilities and helper functions that don't fit into the espejote core library, but are still generally useful for writing Jsonnet code for espejote.

      Documentation is available in the `docs/contrib/lib` directory.
  labels:
    app.kubernetes.io/name: espejote
    app.kubernetes.io/managed-by: kustomize
  name: contrib
spec:
  data:
    accessors.libsonnet: |-
      local d = import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet';

      local getName =
        function(obj) std.get(std.get(obj, 'metadata', {}), 'name', '');

      local getNamespace =
        function(obj) std.get(std.get(obj, 'metadata', {}), 'namespace', '');

      // validateOwner checks that the owner reference is valid and returns an error message if it's not, or null if it is.
      local validateOwner = function(owner, obj)
        local errors = std.filter(
          function(c) !std.isNull(c),
          [
            if std.get(owner, 'apiVersion', '') == '' then
              'owner must have apiVersion',
            if std.get(owner, 'kind', '') == '' then
              'owner must have kind',
            if getName(owner) == '' then
              'owner must have name',
            if std.get(std.get(owner, 'metadata', {}), 'uid', '') == '' then
              'owner must have uid',
            local ownerNamespace = getNamespace(owner);
            local objNamespace = getNamespace(obj);
            if ownerNamespace != '' then
              if objNamespace == '' then
                "cluster-scoped resource must not have a namespace-scoped owner, owner's namespace %s" % ownerNamespace
              else if ownerNamespace != objNamespace then
                "cross-namespace owner references are disallowed, owner's namespace %s, obj's namespace %s" % [ownerNamespace, objNamespace],
          ]
        );

        if std.length(errors) > 0 then
          'Error validating owner reference:\n' + std.join('', std.map(function(e) '* %s\n' % e, errors))
        else
          null
      ;


      {
        '#': d.pkg(
          name='accessors',
          url='accessors.libsonnet',
          help='`accessors` implements accessors for Kubernetes manifests/ objects.',
        ),

        '#inDelete': d.fn(|||
          Checks if an object is in the process of being deleted.
        |||, [
          d.arg('obj', d.T.object),
        ]),
        inDelete: function(obj) std.get(std.get(obj, 'metadata', {}), 'deletionTimestamp', '') != '',

        '#getName': d.fn(|||
          Gets the name of an object. Empty string is returned if the name is not set.
        |||, [
          d.arg('obj', d.T.object),
        ]),
        getName: getName,

        '#getNamespace': d.fn(|||
          Gets the namespace of an object. Empty string is returned if the namespace is not set.
        |||, [
          d.arg('obj', d.T.object),
        ]),
        getNamespace: getNamespace,

        '#getLabel': d.fn(|||
          Gets the value of a label from an object. Null is returned if the label is not set.
        |||, [
          d.arg('obj', d.T.object),
          d.arg('label', d.T.string),
        ]),
        getLabel: function(obj, label) std.get(std.get(std.get(obj, 'metadata', {}), 'labels', {}), label, null),

        '#getAnnotation': d.fn(|||
          Gets the value of an annotation from an object. Null is returned if the annotation is not set.
        |||, [
          d.arg('obj', d.T.object),
          d.arg('annotation', d.T.string),
        ]),
        getAnnotation: function(obj, annotation) std.get(std.get(std.get(obj, 'metadata', {}), 'annotations', {}), annotation, null),

        '#setOwnerReference': d.fn(|||
          Sets an owner reference on an object.
          The owner reference is validated and an error message is returned if it's invalid.

          This function assumes the owner reference is a static patch and thus does not check for existing owner references on the object.

          If `controller` is true, the owner reference will be set as a controller reference by setting the `controller` and `blockOwnerDeletion` fields to true.

          Returns an array of `[updatedObject, errorString]`.
          If the owner reference is valid, `errorString` will be null.


          ```jsonnet
            local obj = errors.fromTuple(accessors.setOwnerReference(
              owner,
              {
                apiVersion: 'v1',
                kind: 'ConfigMap',
                metadata: {
                  name: 'object',
                },
              },
            )).unpack();
          ```
        |||, [
          d.arg('owner', d.T.object),
          d.arg('obj', d.T.object),
          d.arg('controller', d.T.boolean, false),
        ]),
        setOwnerReference: function(owner, obj, controller=false)
          local validationError = validateOwner(owner, obj);
          if !std.isNull(validationError) then
            [obj, validationError]
          else
            [
              obj {
                metadata+: {
                  ownerReferences+: [{
                    apiVersion: owner.apiVersion,
                    kind: owner.kind,
                    name: owner.metadata.name,
                    uid: owner.metadata.uid,
                    [if controller then 'blockOwnerDeletion']: true,
                    [if controller then 'controller']: true,
                  }],
                },
              },
              null,
            ],
      }
    errors.libsonnet: |-
      local d = import 'github.com/jsonnet-libs/docsonnet/doc-util/main.libsonnet';

      local result = {
        local this = self,
        '#unwrap': d.fn(|||
          Unwraps the result, returning the contained value if it's `ok`, or throwing an error if it's `err`.
        |||),
        unwrap: function()
          if this._type == 'ok' then
            this._result
          else
            error this._error
        ,
        '#unwrapOr': d.fn(|||
          Unwraps the result, returning the contained value if it's `ok`, or returning a default value if it's `err`.
        |||, [
          d.arg('or', d.T.any),
        ]),
        unwrapOr: function(or)
          if this._type == 'ok' then
            this._result
          else
            or
        ,
        '#match': d.fn(|||
          Matches on the result, calling `ok(value)` if it's `ok`, or `err(error)` if it's `err`.

          A new result can be returned from the match functions to chain operations, or any value can be returned to break the chain.
          Both functions can be omitted.
          `ok` defaults to returning a ok result with the value, and `err` defaults to returning an err result with the error message.
        |||, [
          d.arg('ok', d.T.func),
          d.arg('err', d.T.func),
        ]),
        match: function(
          ok=function(res) result {
            _result: res,
            _type: 'ok',
          }, err=function(msg) result {
            _error: msg,
            _type: 'error',
          }
              )
          if this._type == 'ok' then
            ok(this._result)
          else
            err(this._error),
      };

      local ok(any) = result {
        _result: any,
        _type: 'ok',
      };

      local err(msg) = result {
        _error: msg,
        _type: 'error',
      };

      local fromTuple(tuple) =
        if std.length(tuple) == 2 then
          if tuple[1] == null then
            ok(tuple[0])
          else
            err(tuple[1])
        else
          error 'Invalid tuple length: expected 2, got %s' % std.length(tuple);

      {
        '#': d.pkg(
          name='errors',
          url='errors.libsonnet',
          help=|||
            `errors` Implements error handling utilities.

            Jsonnet errors immediately terminate the program, which makes it difficult to handle errors gracefully.
            This library provides a `result` type that can be used to represent either a successful result or an error,
            allowing you to handle errors without crashing the entire program.

            It is inspired by Rust's `Result` type.

            ```jsonnet
            local errors = import 'errors.libsonnet';

            local divide = function(a, b)
              if b == 0 then
                errors.err('division by zero')
              else
                errors.ok(a / b)
              ;

            local result1 = divide(10, 2); // ok(5)
            local result2 = divide(10, 0); // err('division by zero')

            local value1 = result1.unwrapOr(0); // 5
            local value2 = result2.unwrapOr(0); // 0

            local value1 = result1.unwrap(); // 5
            local value2 = result2.unwrap(); // throws an error with message 'division by zero'

            local message1 = result1.match(
              ok=function(value) 'Result is ' + std.toString(value),
              err=function(msg) 'Error: ' + msg,
            ); // 'Result is 5'
            ```
          |||,
        ),
        '#ok': d.fn(|||
          Ok creates a successful result containing the given value.
        |||, [
          d.arg('any', d.T.any),
        ]),
        ok: ok,
        '#err': d.fn(|||
          Err creates an error result containing the given error message.
        |||, [
          d.arg('msg', d.T.string),
        ]),
        err: err,
        '#fromTuple': d.fn(|||
          Creates a result from a tuple of the form `[value, error]`.
          If the error is `null`, it returns an `ok` result with the value.
          Otherwise, it returns an `err` result with the error message.

          ```jsonnet
            local val = errors.fromTuple([42, null]); // ok(42)
            local err = errors.fromTuple([42, 'something went wrong']); // err('something went wrong')
          ```
        |||, [
          d.arg('tuple', d.T.array),
        ]),
        fromTuple: fromTuple,
        '#result': d.obj(
          'A result can be either a successful value or an error message. It provides methods to handle both cases. Should be created using `ok`, `err`, or `fromTuple` functions.',
        ),
        result: result,
      }
